### ISSUE TITLE
Adding new MFEs causes `dev start` to fail with image pull error

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/tutor-mfe#111]
The README [describes how to add extra MFEs](https://github.com/overhangio/tutor-mfe#adding-new-mfes) to the plugin. I've used this method successfully in the past.

I'm trying to run the [tutor-contrib-library-authoring-mfe plugin](https://github.com/openedx/frontend-app-library-authoring/tree/master/tutor-contrib-library-authoring-mfe), which [uses that same method](https://github.com/openedx/frontend-app-library-authoring/blob/a5ae26ae517cc71f86358ef52dd8650e71ab67b9/tutor-contrib-library-authoring-mfe/tutor_library_authoring_mfe/plugin.py#L30-L44) in order to add frontend-app-library-authoring. I ran the following:
```
pip install -e 'git+https://github.com/openedx/frontend-app-library-authoring.git#egg=tutor-contrib-library-authoring-mfe&subdirectory=tutor-contrib-library-authoring-mfe'
tutor plugins enable library_authoring_mfe
tutor config save
tutor dev init -l library_authoring_mfe
```
This all worked fine. However when I try to start the MFE:
```
tutor dev start library-authoring
```
I get:
```
Pulling library-authoring (docker.io/overhangio/openedx-library-authoring-dev:15.0.5)...
ERROR: pull access denied for overhangio/openedx-library-authoring-dev, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Error: Command failed with status 1: docker-compose -f /home/kyle/openedx/tutor-root/env/local/docker-compose.yml -f /home/kyle/openedx/tutor-root/env/dev/docker-compose.yml -f /home/kyle/openedx/tutor-root/env/dev/docker-compose.tmp.yml --project-name tutor_nightly_dev up --remove-orphans --build library-authoring
```

It looks like Tutor is trying to pull the non-existent `docker.io/overhangio/openedx-library-authoring-dev` image. I think it should try to instead *build* that image, since we wouldn't expect it to exist in the overhangio DockerHub repo.

Looking at `$(tutor config printroot)/env/dev/docker-compose.yml`, I see:
```yml
  library-authoring:
      image: "docker.io/overhangio/openedx-library-authoring-dev:15.0.5"
      ports:
          - "3001:3001"
      stdin_open: true
      tty: true
      volumes:
          - ../plugins/mfe/apps/mfe/webpack.dev-tutor.config.js:/openedx/app/webpack.dev-tutor.config.js:ro
      restart: unless-stopped
      depends_on:
          - lms
```
I suspect this is related the the [MFE runtime config change](https://github.com/overhangio/tutor-mfe/pull/69), because up until that change, *all* MFE images were build locally; none of them were pulled down from DockerHub.

tutor version: 15.2.0-nightly
tutor-mfe version: 15.0.5 nightly
